DROP TABLE IF EXISTS `animals`;

CREATE TABLE IF NOT EXISTS `animals` (
  `id`      INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  
  `animal_guid` BINARY(16) NOT NULL,
  `animal_key`  VARCHAR(255) NOT NULL,#test end of line comment
  `description` TEXT,

  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;