DROP TABLE IF EXISTS `animal_types`;

CREATE TABLE IF NOT EXISTS `animal_types` (
  `id`      INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  
  `animal_type_guid` BINARY(16) NOT NULL,
  `type`             VARCHAR(255) NOT NULL,

  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;#